### ISSUE TITLE
Message Blocking

### ISSUE THREAD

**Issue by ngbeslhang** [ngbeslhang/Rotom#12]
- YAML-based configuration:
```yml
discord:
    block: true
    # USE EITHER BLACKLIST OR WHITELIST
    # If both are used, only the whitelist will be used instead
    # In either invite code or ID
    whitelist:
        - pokemon
        - discord-developers
        - discord-api
        - 0cDvIgU2voWn4BaD
    blacklist:
        - quak

links:
   # TBD
```
