### ISSUE TITLE
Smart cog loading

### ISSUE THREAD

**Issue by ngbeslhang** [ngbeslhang/Rotom#13]
- Loads cogs on initialization based on cog settings inside the config YAML file. e.g. if the config file has global level keys like this...
```yaml
db_rethinkdb:
    name: rotom
    host: localhost
    port: 28015

lang:
    default: enUS

moderation:
    defaults:
        admin:
        - Rotom Admin
        mod:
        - Rotom Mod
```
...`db_rethinkdb`, `lang` and `moderation` cogs will be automatically loaded.

You can disable it (and by default it's disabled) by setting `bot.cogs.smart_loading` to false.
